# Generated by Django 5.0.6 on 2024-07-08 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='subject_id',
            new_name='subject',
        ),
    ]
