# Generated by Django 5.0.7 on 2024-07-16 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('score', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.IntegerField()),
                ('position', models.CharField(max_length=100)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scores', to='student.student')),
            ],
        ),
    ]
